name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default resource group
        run: az config set defaults.location=ukwest defaults.group=test
      - name: set file permissions
        run: chmod -R 744 session0*;ls -lR
      - name: Run 02
        run: ./session07/02/script2.sh -f session07/02/parameters_file
      - name: Run 03
        run: ./session07/03/script3.sh -f session07/03/parameters_file
      - name: Run 04
        run: ./session07/04/script4.sh -f session07/04/parameters_file
      - name: Run 05
        run: ./session07/05/script5.sh -f session07/05/parameters_file
      - name: Run Session08
        run: ./session08/script.sh -f session08/parameters_file
      - name: Run Session09
        run: ./session09/02/script.sh -f session09/02/parameters_file
      - name: Run Session09
        run: ./session09/03/script.sh -f session09/03/parameters_file
      - name: Run Session09
        run: ./session09/04/script.sh -f session09/04/parameters_file
